<?php

class ContactForm extends WP_Widget {

	/**
	 * ContactForm constructor.
	 */
	public function __construct() {
		parent::__construct( 'tech-interview-contact', __('Contact Form') );

		$this->add_shortcodes();
	}

	/**
	 * @param array $args
	 * @param array $instance
	 */
	function widget( $args, $instance ) {
		parent::widget( $args, $instance ); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $new_instance
	 * @param array $old_instance
	 *
	 * @return array
	 */
	function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $instance
	 *
	 * @return string
	 */
	function form( $instance ) {
		require_once('contact-form-display.php');
	}

	/**
	 * Register shortcodes for widget
	 */
	function add_shortcodes() {
		add_shortcode('contact-form', [$this, 'form']);
	}
}